Repository planetarium/pn-chrono, pull requests merged in 2022-09, with the labels that each got.

#2 Adjust descriptions
  Gruntfile.js
  README.md
  package-lock.json
  package.json
Labels: Small

#6 Fix GraphQL schema & tx retrieval
  background/src/api/graphql.js
  background/src/storage/storage.js
Labels: Extra Small

#7 Remove unneeded tests
  background/test/api/graphql.test.js
  background/test/wallet/wallet.test.js
  popup/test/views/BridgeWNCG.test.js
Labels: Small

#8 Some more rebranding
  background/test/wallet/wallet.test.js
  extension/_locales/en/messages.json
  extension/_locales/ko/messages.json
  popup/src/views/Index.vue
  popup/src/views/Send.vue
Labels: Extra Small

#13 Wallet usage guide
  USAGE.md
Labels: Small

#12 Remove 0x from private key display
  popup/src/components/AccountManager.vue
Labels: Extra Small

#14 Use @planetarium/tx for creating unsigned tx
  background/package.json
  background/src/api/graphql.js
  background/src/wallet/wallet.js
  background/test/mock.js
  background/test/wallet/wallet.test.js
  popup/src/api/background.js
  popup/src/views/BridgeWNCG.vue
  popup/src/views/Send.vue
  vendor/planetarium-tx-0.0.0.tgz
Labels: Medium

#5 Merge from jckdotim/fix-errata
  extension/_locales/ko/messages.json
Labels: Extra Small
